apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotsadm-web
spec:
  selector:
    matchLabels:
      app: kotsadm-web
  template:
    metadata:
      labels:
        app: kotsadm-web
    spec:
      containers:
        - name: kotsadm-web
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
            limits:
              cpu: 20m
              memory: 45Mi
          image: kotsadm-web
          imagePullPolicy: IfNotPresent
