name: 'Build kotsadm image'
description: 'Composite action for building kotsadm image for e2e tests'
inputs:
  image-name:
    description: The full image name
    required: true

runs:
  using: "composite"
  steps:
    - uses: chainguard-dev/actions/melange-build@main
      with:
        config: melange.yaml
        archs: x86_64
        sign-with-temporary-key: true

    - uses: chainguard-images/actions/apko-publish@main
      with:
        config: apko.yaml
        archs: x86_64
        tag: ${{ inputs.image-name }}
        vcs-url: true
