name: 'KOTS Setup Compatibility Matrix'
description: 'Composite action for creating a compatibility matrix cluster and exporting the kubeconfig'
inputs:
  api-token:
    description: 'Replicated API Token'
    required: true

  kubernetes-distribution:
    description: 'Kubernetes distribution'
    default: 'k3s'
    required: false

  kubernetes-version:
    description: 'Kubernetes version'
    required: true

  ttl:
    description: 'TTL for the cluster'
    default: '60m'
    required: false

runs:
  using: "composite"
  steps:
    - name: Create Cluster 
      id: create-cluster 
      uses: replicatedhq/compatibility-actions/create-cluster@v0 
      with: 
        api-token: ${{ inputs.api-token }}
        kubernetes-distribution: ${{ inputs.kubernetes-distribution }}
        kubernetes-version: ${{ inputs.kubernetes-version }}
        cluster-name: ${{ github.ref_name }}-${{ inputs.kubernetes-distribution }}-${{ inputs.kubernetes-version }}
        ttl: ${{ inputs.ttl }}

    - name: Write and Export KUBECONFIG
      run: |
        mkdir -p $HOME/.kube
        echo "${{ steps.create-cluster.outputs.cluster-kubeconfig }}" > $HOME/.kube/config
        echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV
      shell: bash
