apiVersion: k3d.io/v1alpha5
kind: Simple
servers: 1
network: k3d
kubeAPI:
  hostIP: "0.0.0.0"
  hostPort: "6443"
ports:
  - port: 30880:30880
    nodeFilters:
      - server:*
  - port: 30881:30881
    nodeFilters:
      - server:*
  - port: 32000:32000
    nodeFilters:
      - server:*
options:
  k3d:
    wait: true
    timeout: "60s"
  k3s:
    extraArgs:
      - arg: --tls-san=127.0.0.1
        nodeFilters:
          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
