apiVersion: apps/v1
kind: Deployment
metadata:
  name: kotsadm
spec:
  selector:
    matchLabels:
      app: kotsadm
  template:
    metadata:
      labels:
        app: kotsadm
    spec:
      restartPolicy: Always
      containers:
        - name: kotsadm
          image: localhost:32000/kotsadm-api
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - name: http
              containerPort: 3000
            - name: dlv
              containerPort: 30001
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
