apiVersion: v1
kind: Service
metadata:
  name: kotsadm
  labels:
    app: kotsadm
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: NodePort
  ports:
  - name: http
    port: 3000
    targetPort: http
    nodePort: 30000
  selector:
    app: kotsadm
