name: kurl-addon-publish

on:
  workflow_dispatch:
    inputs:
      addon_version:
        type: string
        description: "Kots version (without the 'v')."
        required: true
  release:
    types:
      - published

concurrency: kurl-addon-publish-${{ inputs.addon_version }}

jobs:
  publish-kots-addon:
    uses: replicatedhq/kots/.github/actions/kurl-addon-kots-publish@emosbaugh/sc-55217/test-kurl-addon-on-release # TODO: change
    with:
      addon_version: "${{ inputs.addon_version || github.ref_name }}"
      s3_prefix: ""
      priority: 1
      testgrid_api_token: ${{ secrets.TESTGRID_PROD_API_TOKEN }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.KURL_ADDONS_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.KURL_ADDONS_AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
