name: license-compliance

on:
  pull_request:
  workflow_dispatch:
    secrets:
      FOSSA_API_KEY: 
        required: true

jobs:
  license-compliance:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run FOSSA scan
        uses: fossas/fossa-action@v1.3.1
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
      - name: Run FOSSA test
        uses: fossas/fossa-action@v1.3.1
        with:
          api-key: ${{ secrets.FOSSA_API_KEY }}
          run-tests: true
