name: regression-test-trigger1

on:
  push:
    branches:
      - seanrester/sc-48196/update-serial-regression-tests-to-run-in

jobs:
  generate-tag:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.NIGHTLY_GH_PAT }} # needed to git push nightly tag

    - name: Get tags
      id: get_tag
      uses: ./actions/version-tag

    - name: Push tag
      env:
        GIT_TAG: ${{ steps.get_tag.outputs.GIT_TAG }}
      run: |
        git tag $GIT_TAG
        git push origin $GIT_TAG
