name: regression-test-cleanup

on:
  workflow_dispatch:
  push:
    branches:
      - seanrester/sc-48196/update-serial-regression-tests-to-run-in
  schedule:
    - cron: '0 * * * *'

env:
  AWS_DEFAULT_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.E2E_TESTIM_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.E2E_TESTIM_AWS_SECRET_ACCESS_KEY }}
  E2E_TESTIM_AWS_ACCESS_KEY_ID: ${{ secrets.E2E_TESTIM_AWS_ACCESS_KEY_ID }}
  E2E_TESTIM_AWS_SECRET_ACCESS_KEY: ${{ secrets.E2E_TESTIM_AWS_SECRET_ACCESS_KEY }}
  KOTS_BUILD_STATUS_SLACK_WEBHOOK_URL: ${{ secrets.KOTS_BUILD_STATUS_SLACK_WEBHOOK_URL }}

jobs:
  generate-tag:
    runs-on: ubuntu-20.04
    container:
      image: hashicorp/terraform:1.0.7
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: replicatedhq/kots-regression-automation
          token: ${{ secrets.E2E_GH_PAT }}
          ref: seanrester/sc-48196/update-serial-regression-tests-to-run-in
      - name: View context attributes
        uses: ./actions/clean-up