name: helm-chart-release

on:
  release:
    types: [released]

jobs:
  tag-helm-chart:
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout Chart
          if: github.ref_type == 'tag'
          uses: actions/checkout@v3
          with:
            repository: replicatedhq/kots-helm
            token: ${{ secrets.GH_PAT }}
            ref: main
        - name: Tag Chart
          run: |
            git tag ${GITHUB_REF}
            git push origin ${GITHUB_REF}